locallibrary/catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('book/create/', views.BookCreate.as_view(), name='book-create'),
    path('book-select/', views.select_book, name='book-select'),
    path('book/<int:pk>/update/', views.BookUpdateView.as_view(), name='book-update'),
    path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='book-delete'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
    path('author/', views.AuthorListView.as_view(), name='author'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('author-select/', views.select_author, name='author-select'),
    path('author/<int:pk>/update/', views.AuthorUpdateView.as_view(), name='author-update'), 
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
    path('genre/', views.GenreListView.as_view(), name='genre'),
    path('genres/<int:pk>', views.GenreDetailView.as_view(), name='genre-detail'),
    path('language/', views.LanguageListView.as_view(), name='language'),
    path('language/<int:pk>/', views.LanguageDetailView.as_view(), name='language-detail'),
    path('mybooks/', views.LoaneBooksByUserListView.as_view(), name='my-borrowed'),
    path('allbooks/', views.BooksCheckedOutByAllUsers.as_view(), name='all-borrowed'),
]

locallibrary/locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin




urlpatterns = [
    path('admin/', admin.site.urls), 
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

locallibrary/catalog/models.py
from django.db import models
from django.urls import reverse #Used to generate URLs by reversing the URL patterns
import uuid # Requerida para las instancias de libros únicos
from datetime import date
from django.contrib.auth.models import User


# Create your models here.
class Genre(models.Model):
    """Modelo que representa un género literario (p. ej. ciencia ficción, poesía, etc.)."""
    name = models.CharField(max_length=200, help_text="Ingrese el nombre del género (p. ej. Ciencia Ficción, Poesía Francesa etc.)")

    class Meta:
        ordering = ["name"]

    def __str__(self):
        """Cadena que representa a la instancia particular del modelo (p. ej. en el sitio de Administración)"""
        return self.name
    
    def get_absolute_url(self):
        return reverse('genre-detail', args=[str(self.id)])
    

    


class Language(models.Model):
    """Modelo que representa un género literario (p. ej. ciencia ficción, poesía, etc.)."""
    name = models.CharField('Language', max_length=200, help_text="Ingrese el nombre del idioma")

    def __str__(self):
        """Cadena que representa a la instancia particular del modelo (p. ej. en el sitio de Administración)"""
        return self.name
    
    def get_absolute_url(self):
        return reverse('language-detail', args=[str(self.id)])
    
    def display_Language(self):
        if self.name:
            return','.join([name.name for name in self.name.all()[:3]])
        return 'No hay Idiomas'
    display_Language.short_description='Language'



class Book(models.Model):
    """Modelo que representa un libro (pero no un Ejemplar específico)."""
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True, related_name='books')
    # ForeignKey, ya que un libro tiene un solo autor, pero el mismo autor puede haber escrito muchos libros.
    # 'Author' es un string, en vez de un objeto, porque la clase Author aún no ha sido declarada.
    summary = models.TextField(max_length=1000, help_text="Ingrese una breve descripción del libro")
    isbn = models.CharField('ISBN',max_length=14, help_text='13 Caracteres <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text="Seleccione el genero para este libro" )
    # ManyToManyField, porque un género puede contener muchos libros y un libro puede cubrir varios géneros.
    # La clase Genre ya ha sido definida, entonces podemos especificar el objeto arriba.py
    language = models.ManyToManyField(Language, help_text="Seleccione un idioma para este libro")

    class Meta:
        ordering = ["title"]
    

    def __str__(self):
        """String que representa al objeto Book"""
        return self.title


    def get_absolute_url(self):
        """Devuelve el URL a una instancia particular de Book"""
        return reverse('book-detail', args=[str(self.id)])
    
    
    def display_genre(self):
        if self.genre:
            return','.join([genre.name for genre in self.genre.all()[:3]])
        return 'No Genre'
    display_genre.short_description ='Genre'

    def display_language(self): 
        if self.language:
            return ', '.join(language.name for language in self.language.all()[:3])
        return 'No language'
    display_genre.short_description = 'Language'



class BookInstance(models.Model):
    """Modelo que representa una copia específica de un libro (i.e. que puede ser prestado por la biblioteca)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="ID único para este libro particular en toda la biblioteca")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField('Observación',max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length=1, 
                             choices=LOAN_STATUS,
                             blank=True, default='m',
                             help_text='Disponibilidad del libro')

    class Meta:
        ordering = ["due_back"]


    def __str__(self):
        """String para representar el Objeto del Modelo"""
        return '%s (%s)' % (self.id,self.book.title)
    
    @property
    def is_overdue(self): 
        if self.due_back and date.today() > self.due_back:
             return True 
        return False


class Author(models.Model):
    """Modelo que representa un autor"""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died',null=True, blank=True)

    
    class Meta:
        ordering = ["last_name", "first_name"]

    def get_absolute_url(self):
        """Retorna la url para acceder a una instancia particular de un autor."""
        return reverse('author-detail', args=[str(self.id)])
    
    def __str__(self):
        """String para representar el Objeto Modelo"""
        return '%s, %s' % (self.last_name, self.first_name)

locallibrary/catalog/forms.py
from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
import datetime #for checking renewal date range.
from .models import BookInstance, Author, Book

class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        #Check date is not in past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        #Check date is in range librarian allowed to change (+4 weeks).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data
    
    class Meta:
        model= BookInstance
        fields = ['due_back',]
        labels = {'due_back': ('Enter a date between now and 4 weeks (default 3).'),}

class AuthorSelectForm(forms.Form):
    author = forms.ModelChoiceField(queryset=Author.objects.all(), label='Seleccionar Autor')

class BookSelectForm(forms.Form):
    book = forms.ModelChoiceField(queryset=Book.objects.all(), label='Seleccionar Book')

locallibrary/catalog/views.py
from django.urls import reverse
from django.views import generic
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
# Create your views here.
from .models import Book, Author, BookInstance, Genre, Language


def index(request):  
    """Función vista para la página inicio del sitio. """ 
    # Contadores de registros  
    num_books = Book.objects.all().count() 
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    num_authors = Author.objects.count()
    num_genre = Genre.objects.all().count() 
    
    num_visits= request.session.get('num_visits', 0)
    num_visits+=1
    request.session['num_visits']=num_visits


    # Renderiza la plantilla con los datos  
    return render( 
        request,  
        'index.html',  
        context={'num_books':num_books,
                 'num_instances':num_instances,
                 'num_instances_available':num_instances_available,
                 'num_authors':num_authors,
                 'num_genre': num_genre,
                 'num_visits': num_visits,
                 }
    )




class BookListView(LoginRequiredMixin, generic.ListView):
    model= Book
    template_name='catalog/book_list.html'
    paginate_by = 10
    
    
    def get_queryset(self):
        return Book.objects.all()
    
    def get_context_data(self, **kwargs):
        context = super(BookListView, self).get_context_data(**kwargs)
        context['some_data'] = 'Estos son solo algunos datos'
        return context
    

class BookDetailView(generic.DetailView):
    model = Book
    def get_queryset(self):
        return Book.objects.all()
    

class AuthorListView(LoginRequiredMixin, generic.ListView):
    model= Author
    paginate_by = 10
    template_name='catalog/author_list.html'

    def get_queryset(self):
        return Author.objects.all()

    def get_context_data(self, **kwargs):
        context = super(AuthorListView, self).get_context_data(**kwargs)
        context['some_data'] = 'Estos son solo algunos datos'
        return context


class AuthorDetailView(LoginRequiredMixin, generic.DetailView):  
    model= Author
    template_name='catalog/author_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['book_list'] = Book.objects.filter(author=self.object)
        return context


class GenreListView(LoginRequiredMixin, generic.ListView):
    model = Genre
    template_name='catalog/genre_list.html'



class GenreDetailView(generic.DetailView):
    model = Genre
    template_name='catalog/genre_detail.html'

    def get_context_data(self, **kwargs): 
        context = super().get_context_data(**kwargs)
        context['book_list'] = Book.objects.filter(genre=self.object)
        return context
    

class LanguageListView(LoginRequiredMixin, generic.ListView):
    model = Language
    template_name='catalog/language_list.html'

class LanguageDetailView(generic.DetailView):
    model = Language
    template_name='catalog/language_detail.html'
    
    def get_context_data(self, **kwargs): 
        context = super().get_context_data(**kwargs)
        context['book_list'] = Book.objects.filter(language=self.object)
        return context


class LoaneBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """vista generica basada en clases que enumera los libros prestados al usuario actual."""
    model=BookInstance
    template_name='catalog/bookinstance_list_borrowed_user.html'
    paginate_by=10
    
    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')
    
class BooksCheckedOutByAllUsers(LoginRequiredMixin,generic.ListView):
    model = BookInstance
    template_name = 'catalog/list_of_books_checked_out_by_all_users.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').select_related('borrower').order_by('due_back')


from django.contrib.auth.decorators import permission_required

from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
import datetime

from .forms import RenewBookForm, AuthorSelectForm, BookSelectForm

@permission_required('catalog.set_book_as_returned')
def renew_book_librarian(request, pk):
    """
    View function for renewing a specific BookInstance by librarian
    """
    book_inst=get_object_or_404(BookInstance, pk = pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewBookForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_inst.due_back = form.cleaned_data['renewal_date']
            book_inst.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('all-borrowed') )

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date,})

    return render(request, 'catalog/book_renew_librarian.html', {'form': form, 'bookinst':book_inst})




class AuthorCreate(LoginRequiredMixin, CreateView):
    model= Author
    fields= '__all__'
    initial={'date_of_death': '05/05/2018',}



def select_author(request):
    selected_author=None
    if request.method == 'POST':
        form = AuthorSelectForm(request.POST)
        if form.is_valid():
            # Procesar los datos del formulario
            selected_author = form.cleaned_data['author']
            # Hacer algo con el autor seleccionado
            return redirect(reverse('author-update', kwargs={'pk': selected_author.pk}))
    else:
        form = AuthorSelectForm()

    return render(request, 'catalog/author_select_form.html', {'form': form, 'selected_author':select_author})


class AuthorUpdateView(LoginRequiredMixin, UpdateView):
    model= Author
    fields= ['first_name', 'last_name', 'date_of_birth', 'date_of_death']

    template_name = 'catalog/author_update_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author_form'] = AuthorSelectForm()
        return context

class AuthorDelete(LoginRequiredMixin, DeleteView):
    model=Author
    template_name= 'catalog/author_confirm_delete.html'
    success_url=reverse_lazy('author')

class BookCreate(LoginRequiredMixin, CreateView):
    model= Book
    fields = ['title', 'author', 'summary', 'isbn', 'language', 'genre']
    template_name='catalog/book_form.html'


def select_book(request):
    if request.method == 'POST':
        form = BookSelectForm(request.POST)
        if form.is_valid():
            # Procesar los datos del formulario
            selected_book = form.cleaned_data['book']
            # Hacer algo con el autor seleccionado
            return redirect(reverse('book-update', kwargs={'pk': selected_book.pk}))
    else:
        form = BookSelectForm()

    return render(request, 'catalog/book_select_form.html', {'form': form})

class BookUpdateView(LoginRequiredMixin, UpdateView):
    model=Book
    fields= ['title', 'author', 'summary', 'isbn', 'language', 'genre']
    template_name='catalog/book_update_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['book_form'] = BookSelectForm()
        return context

class BookDelete(LoginRequiredMixin, DeleteView):
    model=Book
    template_name= 'catalog/book_confirm_delete.html'
    success_url=reverse_lazy('books')

locallibrary/catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Confirm Delete</h1>

<p>Are you sure you want to delete the author: {{ object }}?</p>

<form method="post">
    {% csrf_token %}
    <button type="submit">Si, Eliminar</button>
    <a href="{% url 'author-update' object.pk %}">Cancelar</a>
</form>
{% endblock %}

locallibrary/catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Author: {{ author.first_name }} {{ author.last_name }}</h1>
  <p>Fecha de Nacimiento: {{ author.date_of_birth }}</p> 
  <p>Fecha de Defunción: {{ author.date_of_death }}</p> 


  <h2> Libros publicados</h2>
  {% if book_list %}
    <ul>
      {% for book in book_list %}
        <li>
          <a href="{{ book.get_absolute_url }}">{{ book.title }}</a></li>
      {% endfor%}
    </ul>
  {% else %}
    <p>No se encontraron libros publicados para este autor.</p>
  {% endif %}
     
  </ul>
{% endblock %}

locallibrary/catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block content %}

<html>
<body>
    <h1>Author Create</h1>
    <form method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        
        <button type="submit">save</button>
    </form>
</body>
</html>
{% endblock %}

locallibrary/catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>List Author</h1>

    {% if author_list %}
    <ul>

      {% for author in author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{author.last_name}} {{author.first_name}}</a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>No hay libros en la biblioteca.</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/author_select_form.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Seleccionar Autor</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Editar</button>
  </form>

{% endblock %}

locallibrary/catalog/templates/catalog/author_update_form.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Actualizar Autor</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar cambios</button>
  </form>

  <h2>Eliminar Autor</h2>
  <a href="{% url 'author-delete' object.pk %}">
    <button type="button">Eliminar</button>
  </a>
{% endblock %}

locallibrary/catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Lista de libros</h1>

    {% if book_list %}
    <ul>

      {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>No hay libros en la biblioteca.</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}
{% block content %}

    <h1>Renew: {{bookinst.book.title}}</h1>
    <p>Borrower: {{bookinst.borrower}}</p>
    <p{% if bookinst.is_overdue %} class="text-danger"{% endif %}>Due date: {{bookinst.due_back}}</p>

    <form action="" method="post">
        {% csrf_token %}
        <table>
          <tr>
            <th><label for="id_renewal_date">Renewal date:</label></th>
            <td>
              <ul class="errorlist">
                <li>Invalid date - renewal in past</li>
              </ul>
              <input
                id="id_renewal_date"
                name="renewal_date"
                type="text"
                value="2015-11-08"
                required />
              <br />
              <span class="helptext">
                Enter date between now and 4 weeks (default 3 weeks).
              </span>
            </td>
          </tr>   
        </table>
        <input type="submit" value="Submit" />
    </form>

{% endblock %}

locallibrary/catalog/templates/catalog/book_select_form.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Seleccionar Book</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Editar</button>
  </form>
{% endblock %}

locallibrary/catalog/templates/catalog/book_update_form.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Actualizar Book</h1>
  <form method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    
    <button type="submit">Guardar cambios</button>
  </form>

  <h2>Eliminar Book</h2>
  <a href="{% url 'book-delete' object.pk %}">
    <button type="button">Eliminar</button>
  </a>
{% endblock %}

locallibrary/catalog/templates/catalog/genre_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Genre: {{ genre.name }}</h1>


  <h2> Libros publicados con este género: </h2>
  {% if book_list %}
    <ul>
      {% for book in book_list %}
        <li>
          <a href="{{ book.get_absolute_url }}">{{ book.title }}</a>
        </li>
      {% endfor%}
    </ul>
  {% else %}
    <p>No se encontraron libros publicados para este genero.</p>
  {% endif %}
     
  </ul>
{% endblock %}

locallibrary/catalog/templates/catalog/genre_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Lista de libros</h1>

    {% if genre_list %}
    <ul>

      {% for genre in genre_list %}
      <li>
        <a href="{{ genre.get_absolute_url }}">{{ genre.name }}</a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>No hay genreros disponibles en la biblioteca.</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/language_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Idioma: {{ language.name }}</h1>


  <h2> Libros disponibles con este Idioma: </h2>
  {% if book_list %}
    <ul>
      {% for book in book_list %}
        <li>
            <a href="{{ book.get_absolute_url }}">{{ book.title }}</a>
        </li>
      {% endfor%}
    </ul>
  {% else %}
    <p>No se encontraron libros disponibles con este idioma.</p>
  {% endif %}
     
  </ul>
{% endblock %}

locallibrary/catalog/templates/catalog/language_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Lista de Idiomas</h1>

    {% if language_list %}
    <ul>

      {% for language in language_list %}
      <li>
        <a href="{{ language.get_absolute_url }}">{{ language.name }}</a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>No hay libros en la biblioteca.</p>
    {% endif %}
{% endblock %}